export const books = [
  {
    id: "1",
    imageURL:
      "https://books.google.com/books/content?id=r_FWWABXjOgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "The Tuscan Sun Cookbook",
    author: "Frances Mayes",
    category: "Cooking",
    ISBN: "6851680504446",
    EAN: "2436925769257052",
    language: "English",
    publication: "2012-03-13",
    description:
      "Tuscan food tastes like itself. Ingredients are left to shine. . . . .So, if on your visit, I hand you an apron, your work will be easy. We`ll start with primo ingredients, a little flurry of activity, perhaps a glass of Vino Nobile di Montepulciano, and soon we'll be carrying platters out the door. We'll have as much fun setting the table as we have in the kitchen. Four double doors along the front of the house open to the outside—so handy for serving at a long table under the stars (or for cooling a scorched pan on the stone wall). Italian Philosophy 101: la casa aperta, the open house. From the Introduction In all of Frances Mayes's bestselling memoirs about Tuscany, food plays a starring role. This cuisine transports, comforts, entices, and speaks to the friendly, genuine, and improvisational spirit of Tuscan life. Both cooking and eating in Tuscany are natural pleasures. In her first-ever cookbook, Frances and her husband, Ed, share recipes that they have enjoyed over the years as honorary Tuscans: dishes prepared in a simple, traditional kitchen using robust, honest ingredients. A toast to the experiences they've had over two decades at Bramasole, their home in Cortona, Italy, this cookbook evokes days spent roaming the countryside for chestnuts, green almonds, blackberries, and porcini; dinner parties stretching into the wee hours, and garden baskets tumbling over with bright red tomatoes. Lose yourself in the transporting photography of the food, the people, and the place, as Frances's lyrical introductions and headnotes put you by her side in the kitchen and raising a glass at the table. From Antipasti (starters) to Dolci (desserts), this cookbook is organized like a traditional Italian dinner. The more than 150 tempting recipes include: · Fried Zucchini Flowers · Red Peppers Melted with Balsamic Vinegar · Potato Ravioli with Zucchini, Speck, and Pecorino · Risotto Primavera · Pizza with Caramelized Onions and Sausage · Cannellini Bean Soup with Pancetta · Little Veal Meatballs with Artichokes and Cherry Tomatoes · Chicken Under a Brick · Short Ribs, Tuscan-Style · Domenica's Rosemary Potatoes · Folded Fruit Tart with Mascarpone · Strawberry Semifreddo · Steamed Chocolate Cake with Vanilla Sauce Frances and Ed also share their tips on stocking your pantry, pairing wines with dishes, and choosing the best olive oil. Learn their time-tested methods for hand rolling pasta and techniques for coaxing the best out of seasonal ingredients with little effort. Throw on another handful of pasta, pull up a chair, and languish in the rustic Italian way of life.",
    price: 12.24,
    currencyCode: "€",
    pagenumber: "224",
    dimensions: { height: 159, width: 128 },
    quantity: 4,
  },
  {
    id: "2",
    imageURL:
      "http://books.google.com/books/content?id=TA9QDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Rails, Angular, Postgres, and Bootstrap",
    author: "David B. Copeland",
    category: "Computers",
    ISBN: "9781680504446",
    EAN: "7474925769257052",
    language: "English",
    publication: "2017-06-22",
    description:
      "Achieve awesome user experiences and performance with simple, maintainable code! Embrace the full stack of web development, from styling with Bootstrap, building an interactive user interface with Angular 4, to storing data quickly and reliably in PostgreSQL. With this fully revised new edition, take a holistic view of full-stack development to create usable, high-performing applications with Rails 5.1. Rails is a great tool for building web applications, but it's not the best at everything. Embrace the features built into your database. Learn how to use front-end frameworks. Seize the power of the application stack through Angular 4, Bootstrap, and PostgreSQL. When used together, these powerful and easy-to-use tools will open you to a new world of possibilities. This second edition is updated to cover Angular - a completely reworked front-end framework - and dives into new Postgres 9.6 features such as UPSERT. Also new is Webpack coverage, to develop the front-end code for your Rails application. Create a usable and attractive login form using Bootstrap's styles, while ensuring the database table backing it is secure using Postgres' check constraints. See how creating an advanced Postgres index for a case-insensitive search speeds up your back end - enabling you to create a dynamic user experience using Angular 4. Create reusable components that bring Bootstrap and Angular together and effectively use materialized views for caching within Postgres. Get your front end working with Webpack, use Postgres' features from migrations, and write unit tests for all of it. All of this within Rails 5.1. You'll gain the confidence to work at every level of the application stack, bringing the right solution to every problem. What You Need: This book covers Postgres 9.5, Rails 5, and Ruby 2.3. You should have some experience with basic Rails concepts and a cursory understanding of JavaScript, CSS, and SQL, but by no means need to be an expert. You'll learn how to install Postgres on your computer or use a free version of it in the cloud.",
    price: 24.12,
    currencyCode: "€",
    pagenumber: "258",
    dimensions: { height: 154, width: 128 },
    quantity: 5,
  },
  {
    id: "3",
    imageURL:
      "https://books.google.com/books/content?id=M3RRDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Speed Cooking",
    author: "Sandra Schumann",
    category: "Cooking",
    ISBN: "6771680504446",
    EAN: "09874925769257052",
    language: "Deutsch",
    publication: "2018-04-10",
    description:
      "Schnell, einfach, klipp und klar: Die besten schnellen Rezepte kochen fast ohne lesen!",
    price: 14.23,
    currencyCode: "€",
    pagenumber: "194",
    dimensions: { height: 162, width: 128 },
    quantity: 10,
  },
  {
    id: "4",
    imageURL:
      "http://books.google.com/books/content?id=STYvzgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    title: "How To Draw AirPlanes For Kids",
    author: "Tore Pirlo",
    category: "Family & Relationships",
    ISBN: "9786780504446",
    EAN: "0094925769257052",
    language: "Deutsch",
    publication: "2021-01-25",
    description:
      "HURRY UP GRAB YOURS NOW REGULAR PRICE 12.99 Scroll to the top of the page and click the ADD TO CART button now",
    price: 22.21,
    currencyCode: "€",
    pagenumber: "42",
    dimensions: { height: 166, width: 128 },
    quantity: 4,
  },
  {
    id: "5",
    imageURL:
      "http://books.google.com/books/content?id=SqtgEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Leila and the Blue Fox",
    author: "Kiran Millwood Hargrave",
    category: "Fiction",
    ISBN: "76881680504446",
    EAN: "0984925769257052",
    language: "English",
    publication: "2022-09-29",
    description:
      "'A captivating tale that glistens with wonder. Leila and Fox will always have a home in my heart' Sophie Anderson 'This is an extraordinary book - wild and beautiful and perfect. The mess and tangle of humanity is so brilliantly contrasted with the wild spirit of nature' Katya Balen Come with an Arctic fox on a breathtaking journey ... an enthralling story from the bestselling, award-winning creators of Julia and the Shark. With dazzling blue and black illustrations and presented as a deluxe hardback with tracing paper inserts, this is a perfect gift for 9+ fans of The Last Bear and A Wolf Called Wander. She was very tired. She lay down, her soft head on her soft paws. The sunset licked her face. The snow covered her like a blanket. Fox wakes, and begins to walk. She crosses ice and snow, over mountains and across frozen oceans, encountering bears and birds beneath the endless daylight of an Arctic summer, navigating a world that is vast, wild and wondrous. Meanwhile, Leila embarks on a journey of her own - finding her way to the mother who left her. On a breathtaking journey across the sea, Leila rediscovers herself and the mother she thought she'd lost, with help from a determined little fox. Based on the true story of an Arctic fox who walked from Norway to Canada in seventy-six days, a distance of two thousand miles, this compelling, emotional and beautifully illustrated story is the perfect gift for 9+ readers. Praise for Julia and the Shark: 'A tale of courage, understanding and compassion' The Observer 'Julia and the Shark is deep, beautiful and true. The art shines and the writing soars. A classic from cover to cover' Eoin Colfer 'A truly beautiful book, with text and illustrations in perfect harmony. A book to treasure!' Jacqueline Wilson",
    price: 12.25,
    currencyCode: "€",
    pagenumber: "128",
    dimensions: { height: 181, width: 128 },
    quantity: 2,
  },
  {
    id: "6",
    imageURL:
      "https://books.google.com/books/content?id=RGOCDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Clean Cooking",
    author: "Elisabeth Johansson",
    category: "Cooking",
    ISBN: "57481680504446",
    EAN: "11225769257052",
    language: "English",
    publication: "2017-02-13",
    description:
      "Learn to both cook and eat clean with fresh fruit and vegetables, wholesome meats, and guilt-free desserts. Cooking without gluten, dairy products, and white sugar is not only easy; the results are also dizzyingly delicious. Clean cooking is a growing trend even among people who aren’t allergic to gluten, dairy products, or white sugar, and it boasts the benefits of slimming you down, giving you more energy, packing your body with nutrients, and making you feel healthier. This gorgeously photographed and styled cookbook embodies the gastronomical mantra of clean cooking and eating, featuring Elisabeth Johansson’s wonderfully fresh smoothies and juices; alternative breakfasts and snacks; new ways of baking bread; hearty vegetarian, seafood, and meaty meals; and sweet offerings that you can enjoy without a guilty conscience. Johansson offers more than 100 recipes for whole meals down to individual sauces and dressings: • Kombucha “sangria” and blueberry smoothie with coconut • Gluten-free hamburgers and “zero-waist” steaks • Carrot, parsnip, and zucchini “spaghetti” with king crab over green curry • Carnitas, guacamole, and mango salsa • Gluten-free scones with fig jam and “raw food” brownies • And many more! Packed with raw superfoods, an abundance of vegetables, and wholesome meat and seafood products, Clean Cooking will show you how to cook, eat, and feel healthy—while enjoying the entire ride there. Skyhorse Publishing, along with our Good Books and Arcade imprints, is proud to publish a broad range of cookbooks, including books on juicing, grilling, baking, frying, home brewing and winemaking, slow cookers, and cast iron cooking. We’ve been successful with books on gluten-free cooking, vegetarian and vegan cooking, paleo, raw foods, and more. Our list includes French cooking, Swedish cooking, Austrian and German cooking, Cajun cooking, as well as books on jerky, canning and preserving, peanut butter, meatballs, oil and vinegar, bone broth, and more. While not every title we publish becomes a New York Times bestseller or a national bestseller, we are committed to books on subjects that are sometimes overlooked and to authors whose work might not otherwise find a home.",
    price: 25.55,
    currencyCode: "€",
    pagenumber: "152",
    dimensions: { height: 162, width: 128 },
    quantity: 3,
  },
  {
    id: "7",
    imageURL:
      "http://books.google.com/books/content?id=ezdeaHfpYPwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Basic Category Theory for Computer Scientists",
    author: "Benjamin C. Pierce",
    category: "Computers",
    ISBN: "9481680504446",
    EAN: "6754925769257052",
    language: "English",
    publication: "1991-08-07",
    description:
      "Basic Category Theory for Computer Scientists provides a straightforward presentation of the basic constructions and terminology of category theory, including limits, functors, natural transformations, adjoints, and cartesian closed categories. Category theory is a branch of pure mathematics that is becoming an increasingly important tool in theoretical computer science, especially in programming language semantics, domain theory, and concurrency, where it is already a standard language of discourse. Assuming a minimum of mathematical preparation, Basic Category Theory for Computer Scientists provides a straightforward presentation of the basic constructions and terminology of category theory, including limits, functors, natural transformations, adjoints, and cartesian closed categories. Four case studies illustrate applications of category theory to programming language design, semantics, and the solution of recursive domain equations. A brief literature survey offers suggestions for further study in more advanced texts. Contents Tutorial • Applications • Further Reading",
    price: 20.12,
    currencyCode: "€",
    pagenumber: "117",
    dimensions: { height: 172, width: 128 },
    quantity: 1,
  },
  {
    id: "8",
    imageURL:
      "http://books.google.com/books/content?id=XH6dW4NV9YgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Parent In Control",
    author: "Gregory Bodenhamer",
    category: "Family & Relationships",
    ISBN: "0981680504446",
    EAN: "0004925769257052",
    language: "English",
    publication: "2010-11-30",
    description:
      "Sound, practical advice on dealing with provocative and manipulative verbal challenges raised by teenagers and early adolescents. Using common scenarios to demonstrate specific parenting techniques, a onetime probation officer offers a straightforward, tested program for maintaining control over adolescents without harsh discipline.",
    price: 21.25,
    currencyCode: "€",
    pagenumber: "192",
    dimensions: { height: 191, width: 128 },
    quantity: 5,
  },
  {
    id: "9",
    imageURL:
      "http://books.google.com/books/content?id=kmrRxqes2B4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Different Engines",
    author: "M. Brake",
    category: "Fiction",
    ISBN: "9001680504446",
    EAN: "67483928565722874",
    language: "English",
    publication: "2007-11-04",
    description:
      "Since its emergence in the seventeenth century, science fiction has been a sustained, coherent and subversive check on the promises and pitfalls of science. In their turn, invention and discovery have forced fiction writers to confront the nature and limits of reality. Different Engines traces the way in which we've imagined the future.",
    price: 12.34,
    currencyCode: "€",
    pagenumber: "274",
    dimensions: { height: 196, width: 128 },
    quantity: 6,
  },
  {
    id: "10",
    imageURL:
      "http://books.google.com/books/content?id=nVZymYAKBfsC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    title: "Cooking Jewish",
    author: "Judy Bart Kancigor",
    category: "Cooking",
    ISBN: "0981680504446",
    EAN: "9704925769257052",
    language: "English",
    publication: "2007-11-22",
    description:
      "Got kugel? Got Kugel with Toffee Walnuts? Now you do. Here's the real homemade Gefilte Fish and also Salmon en Papillote. Grandma Sera Fritkin's Russian Brisket and Hazelnut-Crusted Rack of Lamb. Aunt Irene's traditional matzoh balls and Judy's contemporary version with shiitake mushrooms. Cooking Jewish gathers recipes from five generations of a food-obsessed family into a celebratory saga of cousins and kasha, Passover feasts the holiday has its own chapter and crossover dishes. And for all cooks who love to get together for coffee and a little something, dozens and dozens of desserts: pies, cakes, cookies, bars, and a multitude of cheesecakes; Rugelach and Hamantaschen, Mandelbrot and Sufganyot (Hanukkah jelly doughnuts). Not to mention Tanta Esther Gittel's Husband's Second Wife Lena's Nut Cake. Blending the recipes with over 160 stories from the Rabinowitz family—by the end of the book you'll have gotten to know the whole wacky clan—and illustrated throughout with more than 500 photographs reaching back to the 19th century, Cooking Jewish invites the reader not just into the kitchen, but into a vibrant world of family and friends. Written and recipe-tested by Judy Bart Kancigor, a food journalist with the Orange County Register, who self-published her first family cookbook as a gift and then went on to sell 11,000 copies, here are 532 recipes from her extended family of outstanding cooks, including the best chicken soup ever really from her mother, Lillian. (Or as the author says, \"When you write your cookbook, you can say your mother's is the best.\") Every recipe, a joy in the belly.",
    price: 13.99,
    currencyCode: "€",
    pagenumber: "656",
    dimensions: { height: 155, width: 128 },
    quantity: 8,
  },
  {
    id: "11",
    imageURL:
      "http://books.google.com/books/content?id=8SaP5qqjb0sC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    title: "Flexible Query Answering Systems",
    author: "Henning Christiansen",
    category: "Computers",
    ISBN: "9876680504446",
    EAN: "9870025769257052",
    language: "English",
    publication: "2004-06-17",
    description:
      "This volume constitutes the proceedings of the Sixth International Conferenceon Flexible Query Answering Systems, FQAS 2004, held in Lyon, France, on June 24-26, 2004. FQAS is the premier conference for researchers and practitioners concerned with the vital task of providing easy, flexible, and intuitive access to information for every type of need. This multidisciplinary conference draws on several research areas, including databases, information retrieval, knowledge representation, soft computing, multimedia, and human-computer interaction. With FQAS 2004, the FQAS conference series celebrated its tenth anniversary as it has been held every two years since 1994. The overall theme of the FQAS conferences is innovative query systems aimed at providing easy, flexible, and intuitive access to information. Such systems are intended to facilitate retrieval from information repositories such as databases, libraries, and the Web. These repositories are typically equipped with standard query systems that are often inadequate for users. The focus of FQAS is the development of query systems that are more expressive, informative, cooperative, productive, and intuitive to use.",
    price: 24.05,
    currencyCode: "€",
    pagenumber: "511",
    dimensions: { height: 195, width: 128 },
    quantity: 2,
  },
];
