export const books = [
  {
    id: "1",
    imageURL: "/images/book1.jpeg",
    title: "Rails, Angular, Postgres, and Bootstrap",
    author: "David B. Copeland",
    category: "Computers",
    ISBN: "9781680504446",
    EAN: "7474925769257052",
    language: "English",
    publication: '"2017-06-22',
    description:
      "Achieve awesome user experiences and performance with simple, maintainable code! Embrace the full stack of web development, from styling with Bootstrap, building an interactive user interface with Angular 4, to storing data quickly and reliably in PostgreSQL. With this fully revised new edition, take a holistic view of full-stack development to create usable, high-performing applications with Rails 5.1. Rails is a great tool for building web applications, but it's not the best at everything. Embrace the features built into your database. Learn how to use front-end frameworks. Seize the power of the application stack through Angular 4, Bootstrap, and PostgreSQL. When used together, these powerful and easy-to-use tools will open you to a new world of possibilities. This second edition is updated to cover Angular - a completely reworked front-end framework - and dives into new Postgres 9.6 features such as UPSERT. Also new is Webpack coverage, to develop the front-end code for your Rails application. Create a usable and attractive login form using Bootstrap's styles, while ensuring the database table backing it is secure using Postgres' check constraints. See how creating an advanced Postgres index for a case-insensitive search speeds up your back end - enabling you to create a dynamic user experience using Angular 4. Create reusable components that bring Bootstrap and Angular together and effectively use materialized views for caching within Postgres. Get your front end working with Webpack, use Postgres' features from migrations, and write unit tests for all of it. All of this within Rails 5.1. You'll gain the confidence to work at every level of the application stack, bringing the right solution to every problem. What You Need: This book covers Postgres 9.5, Rails 5, and Ruby 2.3. You should have some experience with basic Rails concepts and a cursory understanding of JavaScript, CSS, and SQL, but by no means need to be an expert. You'll learn how to install Postgres on your computer or use a free version of it in the cloud.",
    price: 24,
    currencyCode: "EUR",
    pagenumber: "258",
  },
  {
    id: "2",
    imageURL: "/images/book2.jpeg",
    title: "Speed Cooking",
    author: "Sandra Schumann",
    category: "Cooking",
    ISBN: "6771680504446",
    EAN: "09874925769257052",
    language: "Deutsch",
    publication: "2018-04-10",
    description:
      "Schnell, einfach, klipp und klar: Die besten schnellen Rezepte kochen fast ohne lesen!",
    price: 14,
    currencyCode: "EUR",
    pagenumber: "194",
  },
  {
    id: "3",
    imageURL: "/images/book3.jpeg",
    title: "How To Draw AirPlanes For Kids",
    author: "Tore Pirlo",
    category: "Family & Relationships",
    ISBN: "9786780504446",
    EAN: "0094925769257052",
    language: "Deutsch",
    publication: '"2021-01-25',
    description:
      "HURRY UP GRAB YOURS NOW REGULAR PRICE 12.99 Scroll to the top of the page and click the ADD TO CART button now",
    price: 22,
    currencyCode: "EUR",
    pagenumber: "42",
  },
  {
    id: "4",
    imageURL: "/images/book4.jpeg",
    title: "The Blue Fox",
    author: "Sjón",
    category: "Fiction",
    ISBN: "76881680504446",
    EAN: "0984925769257052",
    language: "English",
    publication: "2013-04-30",
    description:
      "Set against the stark backdrop of the Icelandic winter, an elusive, enigmatic fox leads a hunter on a transformative quest. At the edge of the hunter's territory, a naturalist struggles to build a life for his charge, a young woman with Down syndrome whom he had rescued from a shipwreck years before. By the end of Sjón's slender, spellbinding fable of a novel, none of their lives will be the same. Winner of the 2005 Nordic Council Literature Prize—the Nordic world's highest literary honor—The Blue Fox is part mystery, part fairy tale, and the perfect introduction to a mind-bending, world-class literary talent.",
    price: 12,
    currencyCode: "EUR",
    pagenumber: "128",
  },
  {
    id: "5",
    imageURL: "/images/book5.jpeg",
    title: "Clean Cooking without gluten and lactose",
    author: "Elisabeth Johansson",
    category: "Cooking",
    ISBN: "57481680504446",
    EAN: "11225769257052",
    language: "English",
    publication: "2017-02-13",
    description:
      "Elisabeth Johansson loves food that is as natural as possible, and her menu includes lots of vegetables, fruit and berries. She avoids dairy products and gluten in her diet. She is completely undogmatic and combines the best of current trends - whether raw food, gluten-free nutrition or sweetening with alternative sweeteners: taste and enjoyment are decisive for her. Her kitchen is absolutely suitable for everyday use, versatile and easy to cook. Be inspired by her delicious recipes for juices and smoothies, vegetables and salad, fish and Meat and heavenly desserts. Clean food full of energy!",
    price: 25,
    currencyCode: "EUR",
    pagenumber: "152",
  },
  {
    id: "6",
    imageURL: "/images/book6.jpeg",
    title: "Basic Category Theory for Computer Scientists",
    author: "Benjamin C. Pierce",
    category: "Computers",
    ISBN: "9481680504446",
    EAN: "6754925769257052",
    language: "English",
    publication: "1991-08-07",
    description:
      "Basic Category Theory for Computer Scientists provides a straightforward presentation of the basic constructions and terminology of category theory, including limits, functors, natural transformations, adjoints, and cartesian closed categories. Category theory is a branch of pure mathematics that is becoming an increasingly important tool in theoretical computer science, especially in programming language semantics, domain theory, and concurrency, where it is already a standard language of discourse. Assuming a minimum of mathematical preparation, Basic Category Theory for Computer Scientists provides a straightforward presentation of the basic constructions and terminology of category theory, including limits, functors, natural transformations, adjoints, and cartesian closed categories. Four case studies illustrate applications of category theory to programming language design, semantics, and the solution of recursive domain equations. A brief literature survey offers suggestions for further study in more advanced texts. Contents Tutorial • Applications • Further Reading",
    price: 20,
    currencyCode: "EUR",
    pagenumber: "117",
  },
  {
    id: "7",
    imageURL: "/images/book7.jpeg",
    title: "Parent In Control",
    author: "Gregory Bodenhamer",
    category: "Family & Relationships",
    ISBN: "0981680504446",
    EAN: "0004925769257052",
    language: "English",
    publication: "2010-11-30",
    description:
      "Sound, practical advice on dealing with provocative and manipulative verbal challenges raised by teenagers and early adolescents. Using common scenarios to demonstrate specific parenting techniques, a onetime probation officer offers a straightforward, tested program for maintaining control over adolescents without harsh discipline.",
    price: 21,
    currencyCode: "EUR",
    pagenumber: "192",
  },
  {
    id: "8",
    imageURL: "/images/book8.jpeg",
    title: "Different Engines",
    author: "M. Brake",
    category: "Fiction",
    ISBN: "9001680504446",
    EAN: "67483928565722874",
    language: "English",
    publication: "2007-11-04",
    description:
      "Since its emergence in the seventeenth century, science fiction has been a sustained, coherent and subversive check on the promises and pitfalls of science. In their turn, invention and discovery have forced fiction writers to confront the nature and limits of reality. Different Engines traces the way in which we've imagined the future.",
    price: 12,
    currencyCode: "EUR",
    pagenumber: "274",
  },
  {
    id: "9",
    imageURL: "/images/book9.jpeg",
    title: "Cooking Jewish",
    author: "Judy Bart Kancigor",
    category: "Cooking",
    ISBN: "0981680504446",
    EAN: "9704925769257052",
    language: "English",
    publication: "2007-11-22",
    description:
      "Got kugel? Got Kugel with Toffee Walnuts? Now you do. Here's the real homemade Gefilte Fish – and also Salmon en Papillote. Grandma Sera Fritkin’s Russian Brisket and Hazelnut-Crusted Rack of Lamb. Aunt Irene's traditional matzoh balls and Judy's contemporary version with shiitake mushrooms. Cooking Jewish gathers recipes from five generations of a food-obsessed family into a celebratory saga of cousins and kasha, Passover feasts – the holiday has its own chapter – and crossover dishes. And for all cooks who love to get together for coffee and a little something, dozens and dozens of desserts: pies, cakes, cookies, bars, and a multitude of cheesecakes; Rugelach and Hamantaschen, Mandelbrot and Sufganyot (Hanukkah jelly doughnuts). Not to mention Tanta Esther Gittel’s Husband’s Second Wife Lena’s Nut Cake. Blending the recipes with over 160 stories from the Rabinowitz family—by the end of the book you'll have gotten to know the whole wacky clan—and illustrated throughout with more than 500 photographs reaching back to the 19th century, Cooking Jewish invites the reader not just into the kitchen, but into a vibrant world of family and friends. Written and recipe-tested by Judy Bart Kancigor, a food journalist with the Orange County Register, who self-published her first family cookbook as a gift and then went on to sell 11,000 copies, here are 532 recipes from her extended family of outstanding cooks, including the best chicken soup ever – really! – from her mother, Lillian. (Or as the author says, \"When you write your cookbook, you can say your mother's is the best.\") Every recipe, a joy in the belly.",
    price: 13,
    currencyCode: "EUR",
    pagenumber: "656",
  },
  {
    id: "10",
    imageURL: "/images/book10.jpeg",
    title: "Flexible Query Answering Systems",
    author: "Henning Christiansen",
    category: "Computers",
    ISBN: "9876680504446",
    EAN: "9870025769257052",
    language: "English",
    publication: "2004-06-17",
    description:
      "ThisvolumeconstitutestheproceedingsoftheSixthInternationalConferenceon Flexible Query Answering Systems, FQAS 2004, held in Lyon, France, on June 24–26, 2004. FQAS is the premier conference for researchers and practitioners concerned with the vital task of providing easy, ?exible, and intuitive access to information for every type of need. This multidisciplinary conference draws on several research areas, including databases, information retrieval, knowledge representation, soft computing, multimedia, and human-computer interaction. With FQAS 2004, the FQAS conference series celebrated its tenth anniversary as it has been held every two years since 1994. The overall theme of the FQAS conferences is innovative query systems aimed at providing easy, ?exible, and intuitive access to information. Such systems are intended to facilitate retrieval from information repositories such as databases, libraries, and the Web. These repositories are typically equipped with standard query systems that are often inadequate for users. The focus of FQAS is the development of query systems that are more expressive, informative, cooperative, productive, and intuitive to use.",
    price: 24,
    currencyCode: "EUR",
    pagenumber: "511",
  },
];
